// <auto-generated />
namespace ZKorsakas.Data.EntityFramework.Tests.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Requiredremoved : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Requiredremoved));
        
        string IMigrationMetadata.Id
        {
            get { return "201703281554060_Required removed"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
